# Generated by Django 5.1.7 on 2025-04-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessorio',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cor',
            name='nome',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='categoria',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='marca',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='nome',
            field=models.CharField(max_length=80),
        ),
    ]
